all:
	gcc -Wall -pedantic -Werror -Wextra -c src/0-print_char.c src/1-print_string.c src/10-cap_string.c src/11-lowercase.c src/12-first_digit.c src/13-absolute.c src/14-uppercase.c src/15-power.c src/16-square_root.c src/17-is_prime_number.c src/18-swap_int.c src/19-str_len.c src/2-print_array.c src/20-reverse_string.c src/21-string_to_integer.c src/22-print_number.c src/23-nconcat_strings.c src/3-concat_string.c src/4-string_copy.c src/5-string_ncopy.c src/6-string_compare.c src/7-reverse_array.c src/8-positive_or_not.c src/9-uppercase_string.c
	ar -rc libholbertonschool.a 0-print_char.o 1-print_string.o 10-cap_string.o 11-lowercase.o 12-first_digit.o 13-absolute.o 14-uppercase.o 15-power.o 16-square_root.o 17-is_prime_number.o 18-swap_int.o 19-str_len.o 2-print_array.o 20-reverse_string.o 21-string_to_integer.o 22-print_number.o 23-nconcat_strings.o 3-concat_string.o 4-string_copy.o 5-string_ncopy.o 6-string_compare.o 7-reverse_array.o 8-positive_or_not.o 9-uppercase_string.o
	rm 0-print_char.o 1-print_string.o 10-cap_string.o 11-lowercase.o 12-first_digit.o 13-absolute.o 14-uppercase.o 15-power.o 16-square_root.o 17-is_prime_number.o 18-swap_int.o 19-str_len.o 2-print_array.o 20-reverse_string.o 21-string_to_integer.o 22-print_number.o 23-nconcat_strings.o 3-concat_string.o 4-string_copy.o 5-string_ncopy.o 6-string_compare.o 7-reverse_array.o 8-positive_or_not.o 9-uppercase_string.o

clean:
	rm libholbertonschool.a

re: 
	all clean